#!/bin/sh
#######################################
# VPN EXception Tool
# Adds a static route to access the printer in the ADC lab at the University of Washington while on a VPN.
# Last Updated: 2013-01-28
#######################################

PRINTER_SUBNET="172.28.244.4/32"
ME=$(/sbin/ip route | grep -E "default via (.*) dev .*" | awk '{print $3}');

if [ "$2" = "vpn-up" ]; then
    /sbin/ip route add $PRINTER_SUBNET via $ME dev p1p1
fi

if [ "$2" = "vpn-down" ]; then
    /sbin/ip route del $PRINTER_SUBNET via $ME dev p1p1
fi

exit 0
